In [6]:
import numpy as np
a = np.array([1,2,3])
b = a   # Here we assigned b to a
b[1] = 10
print(b)  # a and b now both point to the same address so if we change the value at any addresss, it changes at both address
a

[ 1 10  3]


array([ 1, 10,  3])

In [10]:
# To fix the copying issue 
c = np.array([4,5,6])
d = c.copy()  # Now a copy of c is stored in d, both point at different address now
d[1] = 100  
print(c)
d

[4 5 6]


array([  4, 100,   6])