In [5]:
import numpy as np
a = np.array([2,4,6,8], dtype='int32')
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a%2)
print(a**2)
print(a//2)

[ 4  6  8 10]
[0 2 4 6]
[ 4  8 12 16]
[1. 2. 3. 4.]
[0 0 0 0]
[ 4 16 36 64]
[1 2 3 4]


In [11]:
b = np.array([1,0,1,0])
c = np.array([1,2,3,4])
b + a - c  # Operates on each item at same index

array([2, 2, 4, 4])

In [50]:
# Trignometry 

print(np.sin(90*0.01745327778))

0.99999999999912


In [13]:
# Linear Algebra
mat1 = np.full((2,3),2)
mat2 = np.full((3,2),3)
# mat1 * mat2   Gives error
result = np.matmul(mat1,mat2)
print(result)


array([[18, 18],
       [18, 18]])

In [90]:
# Det\erminant
det = np.linalg.det(result)
det

0.0

In [ ]:
# Inverse of a matrix
