In [13]:
import numpy as np
# Import data from file
data = np.genfromtxt('data.txt', delimiter=',', dtype='int32')
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)

In [30]:
# Boolean marking and advanced indexing
print(data > 13)
data[data%2==0]

[[False False False False False False False False False False]
 [False False False False  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
      dtype=int32)

In [38]:
# Index an array with a list
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[[3,6,8]] = 14
arr

array([ 1,  2,  3, 14,  5,  6, 14,  8, 14])